/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmAbsolute
     */
    public frLogin() {
        
        setUndecorated(true);
        initComponents();
       
        initConponentManaily();
        initEvents();
    }
    private void initConponentManaily(){
         btclose.setBackground(new Color(0,0,0,0));
         setLocationRelativeTo(null);
         btlogin.setBackground(new Color(0,0,0,0));
         tfuserName.requestFocus();
    }
    private void initEvents(){
        btcloseEvent();
        btloginEvent();
    }
    private void btloginEvent(){
         btlogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String username = tfuserName.getText();
                String password = String.valueOf(tfpassword.getText());
                boolean isValid = isValidAccount(username, password);
                if (isValid) {
                    frLogin.this.setVisible(false);
                    FmMain frMain = new FmMain();
                    frMain.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Login fail!!!");
                }
            }
            
        });
       
    }
    private boolean isValidAccount(String username , String pass){
        return username.equals("admin") && pass.equals("123123");
        
    }
    private void btcloseEvent(){
        btclose.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
             Icon icon = new ImageIcon(getClass().getResource("/images/64px_flower.png"));
              //final int  Confirm = JOptionPane.showConfirmDialog(null, "do you want to close?");
              final int  Confirm = JOptionPane.showConfirmDialog(null, "do you quan to close", "from system", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE, icon);
              if(Confirm == JOptionPane.YES_OPTION){
                  System.exit(0);
              }
            }
            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfuserName = new javax.swing.JTextField();
        tfpassword = new javax.swing.JTextField();
        btclose = new javax.swing.JToggleButton();
        btlogin = new javax.swing.JButton();
        lblogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfuserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfuserName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfuserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 250, 35));

        tfpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 250, 35));

        btclose.setBackground(new java.awt.Color(255, 0, 0));
        btclose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btclose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 75, 50, 50));

        btlogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 377, 250, 35));

        lblogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ogin.png"))); // NOI18N
        getContentPane().add(lblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserNameActionPerformed

    private void tfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frLogin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btclose;
    private javax.swing.JButton btlogin;
    private javax.swing.JLabel lblogin;
    private javax.swing.JTextField tfpassword;
    private javax.swing.JTextField tfuserName;
    // End of variables declaration//GEN-END:variables
}
