/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.io.File;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import service.TimeService;
import service.TimeServiceImlp;

/**
 *
 * @author Admin
 */
public class EX05 extends javax.swing.JFrame {

   private final Container conn = getContentPane();
   private final TimeService timeService;
   
    public EX05() {
        timeService = new TimeServiceImlp();
        initComponents();
        initComponentsManually();
        initEvents();
    }
    private static final String Image_Path = "D:\\Java\\Workspace\\local_Git\\java07-repository-app\\image\\images";// set đường dẫn

    private void  initComponentsManually(){
        setResizable(false); // khoá phóng to
        setLocationRelativeTo(null); //set cho nằm giữa
        
        Image image = new ImageIcon(Image_Path + File.separator + "48px_love.png").getImage(); // set hình ảnh cho iconImage
        setIconImage(image);
        
        conn.setBackground(Color.BLACK);
        dcend.setDateFormatString("dd-MM-yyyy");
        dcend.setDate(new Date());
    }
    private void initEvents(){
        btLoveEvent();
    }
    
    private void btLoveEvent(){
        btlove.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                final String firstName = tffirstPerson.getText();
                final String secondName =tfSecondPerson.getText();
                final Date start = dcstart.getDate();
                final Date end = dcend.getDate();
                Period period = timeService.getPeriod(start, end);
                
                lbresult.setText("Kết quả là : "
                        + firstName
                        + "&" 
                        + secondName 
                        +"đã quen nhau" 
                        + period.getYears() + "năm," 
                        + period.getMonths()+"tháng,"
                        + period.getDays()+"ngày." );
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitle = new javax.swing.JLabel();
        lbfirstPerson = new javax.swing.JLabel();
        tffirstPerson = new javax.swing.JTextField();
        lbFirstError = new javax.swing.JLabel();
        btlike = new javax.swing.JButton();
        lbFirstError2 = new javax.swing.JLabel();
        btlove = new javax.swing.JButton();
        lbSecondPerson = new javax.swing.JLabel();
        tfSecondPerson = new javax.swing.JTextField();
        lbstart = new javax.swing.JLabel();
        lbend = new javax.swing.JLabel();
        dcstart = new com.toedter.calendar.JDateChooser();
        dcend = new com.toedter.calendar.JDateChooser();
        lbresult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATE-Java07");
        setBackground(new java.awt.Color(0, 0, 0));

        lbtitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbtitle.setForeground(new java.awt.Color(255, 51, 255));
        lbtitle.setText("Love Time Applicaion");

        lbfirstPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbfirstPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbfirstPerson.setText("-Người Thứ Nhất-");

        tffirstPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tffirstPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffirstPersonActionPerformed(evt);
            }
        });

        lbFirstError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 51, 51));
        lbFirstError.setText("Chưa Nhập Tên");

        btlike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_like.png"))); // NOI18N

        lbFirstError2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFirstError2.setForeground(new java.awt.Color(255, 51, 51));
        lbFirstError2.setText("Chưa Nhập Tên");

        btlove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_love.png"))); // NOI18N
        btlove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloveActionPerformed(evt);
            }
        });

        lbSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbSecondPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbSecondPerson.setText("-Người Thứ Hai-");

        tfSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSecondPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondPersonActionPerformed(evt);
            }
        });

        lbstart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbstart.setForeground(new java.awt.Color(255, 255, 255));
        lbstart.setText("Ngày Bắt Đầu");

        lbend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbend.setForeground(new java.awt.Color(255, 255, 255));
        lbend.setText("Ngày Kết Thúc");

        dcstart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dcend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbresult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbresult.setForeground(new java.awt.Color(255, 255, 255));
        lbresult.setText("Kết Quả: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtitle)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbfirstPerson)
                            .addComponent(tffirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFirstError)
                            .addComponent(btlike, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dcstart, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbstart)
                            .addComponent(lbend)
                            .addComponent(dcend, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbSecondPerson)
                            .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFirstError2)
                            .addComponent(btlove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbresult, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcend, dcstart, tfSecondPerson, tffirstPerson});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbtitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSecondPerson)
                        .addComponent(lbstart))
                    .addComponent(lbfirstPerson))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tffirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFirstError)
                            .addComponent(lbend)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSecondPerson)
                            .addComponent(dcstart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(lbFirstError2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dcend, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlike, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlove, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lbresult)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcend, dcstart, tfSecondPerson, tffirstPerson});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tffirstPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffirstPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffirstPersonActionPerformed

    private void tfSecondPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondPersonActionPerformed

    private void btloveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btloveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EX05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EX05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EX05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EX05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EX05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlike;
    private javax.swing.JButton btlove;
    private com.toedter.calendar.JDateChooser dcend;
    private com.toedter.calendar.JDateChooser dcstart;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbFirstError2;
    private javax.swing.JLabel lbSecondPerson;
    private javax.swing.JLabel lbend;
    private javax.swing.JLabel lbfirstPerson;
    private javax.swing.JLabel lbresult;
    private javax.swing.JLabel lbstart;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextField tfSecondPerson;
    private javax.swing.JTextField tffirstPerson;
    // End of variables declaration//GEN-END:variables
}
