/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import service.TimeService;
import service.TimeServiceImpl;

/**
 *
 * @author LONG
 */
public class Ex05 extends javax.swing.JFrame {

    private final Container conn = getContentPane();

    private final TimeService timeService;

    public Ex05() {
        timeService = new TimeServiceImpl();

        initComponents();
        initComponentsManually();
        initEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbFirstPerson = new javax.swing.JLabel();
        tfFirstPerson = new javax.swing.JTextField();
        lbFirstError = new javax.swing.JLabel();
        btLike = new javax.swing.JButton();
        lbSecondPerson = new javax.swing.JLabel();
        tfSecondPerson = new javax.swing.JTextField();
        lbSecondError = new javax.swing.JLabel();
        btLove = new javax.swing.JButton();
        lbStart = new javax.swing.JLabel();
        dcStart = new com.toedter.calendar.JDateChooser();
        lbEnd = new javax.swing.JLabel();
        dcEnd = new com.toedter.calendar.JDateChooser();
        lbResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love - Time Application");

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 0, 204));
        lbTitle.setText("love Time Application");

        lbFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbFirstPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbFirstPerson.setText("Người thứ nhất");

        tfFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbFirstError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 51, 51));
        lbFirstError.setText("Chưa nhập tên");

        btLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_like.png"))); // NOI18N

        lbSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbSecondPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbSecondPerson.setText("Người thứ hai");

        tfSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbSecondError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSecondError.setForeground(new java.awt.Color(255, 51, 51));
        lbSecondError.setText("Chưa nhập tên");

        btLove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_love.png"))); // NOI18N

        lbStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStart.setForeground(new java.awt.Color(255, 255, 255));
        lbStart.setText("Ngày bắt đầu");

        dcStart.setDateFormatString("dd/MM/yyyy");
        dcStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbEnd.setText("Ngày kết thúc");

        dcEnd.setDateFormatString("dd/MM/yyyy");
        dcEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResult.setForeground(new java.awt.Color(255, 255, 255));
        lbResult.setText("Kết quả:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFirstPerson)
                    .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFirstError)
                    .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbStart)
                    .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnd)
                    .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbSecondPerson)
                    .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSecondError)
                    .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lbTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbResult)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFirstPerson)
                    .addComponent(lbStart)
                    .addComponent(lbSecondPerson))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbEnd)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFirstError)
                            .addComponent(lbSecondError))
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(lbResult)
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcEnd, dcStart, tfFirstPerson, tfSecondPerson});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    private void initComponentsManually() {
        setResizable(false);
        setLocationRelativeTo(null);

        Image image = new ImageIcon(getClass().getResource("/images/48px_love.png")).getImage();
        setIconImage(image);

        conn.setBackground(Color.BLACK);

        dcEnd.setDate(new Date());
    }

    private void initEvent() {
        btLoveEvents();
    }

    private void btLoveEvents() {
        btLove.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                final String firstName = tfFirstPerson.getText();
                final String secondName = tfSecondPerson.getText();
                final Date start = dcStart.getDate();
                final Date end = dcEnd.getDate();

                Period period = timeService.getPeriod(start, end);
                lbResult.setText(firstName + " và " + secondName + " bên nhau " + period.getYears() + " năm, " + period.getMonths()
                        + " tháng, " + period.getDays() + " ngày");
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLike;
    private javax.swing.JButton btLove;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbFirstPerson;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSecondError;
    private javax.swing.JLabel lbSecondPerson;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfFirstPerson;
    private javax.swing.JTextField tfSecondPerson;
    // End of variables declaration//GEN-END:variables
}
