/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import service.LoveTimeService;
import service.LoveTimeServiceImpl;

/**
 *
 * @author khanh
 */
public class Ex05 extends javax.swing.JFrame {
    private final LoveTimeService timeService = new LoveTimeServiceImpl();
    Container conn = getContentPane();
    
    public Ex05() {
        initComponents();
        initComponentsManually();
        initEvents();
    }
    
    private void initComponentsManually(){
        setLocationRelativeTo(null);
        setResizable(false);
        Image image = new ImageIcon(getClass().getResource("/images/48px_love.png")).getImage();
        setIconImage(image);
        
        conn.setBackground(Color.black);
        dcEnd.setDate(new Date());
    }
    
    private void initEvents(){
        btnLoveEvents();
    }
    
    private void btnLoveEvents(){
        btnLove.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                final  String firstName = tfFirstPerson.getText();
                final  String secondName = tfSecondPerson.getText();
                final Date start = dcStart.getDate();
                final Date end = dcEnd.getDate();
                
                Period period = timeService.getPeriod(start, end);
                
                lbResult.setText(period.getYears() +" "+period.getMonths()+" "+period.getDays());
            }
            
            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFirstPerson1 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbFirstPerson = new javax.swing.JLabel();
        tfFirstPerson = new javax.swing.JTextField();
        lbFirstError = new javax.swing.JLabel();
        btnLike = new javax.swing.JButton();
        lbSecondPerson = new javax.swing.JLabel();
        tfSecondPerson = new javax.swing.JTextField();
        lbSecondError = new javax.swing.JLabel();
        btnLove = new javax.swing.JButton();
        lbStart = new javax.swing.JLabel();
        dcStart = new com.toedter.calendar.JDateChooser();
        lbEnd = new javax.swing.JLabel();
        dcEnd = new com.toedter.calendar.JDateChooser();
        lbResult = new javax.swing.JLabel();

        lbFirstPerson1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbFirstPerson1.setText("- Người thứ nhất -");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love - Time Application");

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 0, 153));
        lbTitle.setText("Love Time Application");

        lbFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbFirstPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbFirstPerson.setText("Kết quả");

        tfFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfFirstPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstPersonActionPerformed(evt);
            }
        });

        lbFirstError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 0, 0));
        lbFirstError.setText("Chưa Nhập tên");

        btnLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_like.png"))); // NOI18N
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });

        lbSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbSecondPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbSecondPerson.setText("- Người thứ hai -");

        tfSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfSecondPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondPersonActionPerformed(evt);
            }
        });

        lbSecondError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSecondError.setForeground(new java.awt.Color(255, 0, 0));
        lbSecondError.setText("Chưa Nhập tên");

        btnLove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_love.png"))); // NOI18N
        btnLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoveActionPerformed(evt);
            }
        });

        lbStart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbStart.setForeground(new java.awt.Color(255, 255, 255));
        lbStart.setText("Ngày bắt đầu");

        dcStart.setDateFormatString("dd/MM/yyyy");
        dcStart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lbEnd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbEnd.setText("Ngày kết thúc");

        dcEnd.setDateFormatString("dd/MM/yyyy");
        dcEnd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbResult.setForeground(new java.awt.Color(255, 255, 255));
        lbResult.setText("- Người thứ nhất -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFirstError)
                            .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFirstPerson)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbResult)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbStart)
                    .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnd)
                    .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbSecondPerson)
                    .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSecondError)
                    .addComponent(btnLove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbStart)
                            .addComponent(lbResult)
                            .addComponent(lbSecondPerson))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbSecondError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(dcStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60)
                                .addComponent(lbEnd)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnLove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbFirstError)
                        .addGap(116, 116, 116)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFirstPerson)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFirstPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstPersonActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLikeActionPerformed

    private void tfSecondPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondPersonActionPerformed

    private void btnLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnLove;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbFirstPerson;
    private javax.swing.JLabel lbFirstPerson1;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSecondError;
    private javax.swing.JLabel lbSecondPerson;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfFirstPerson;
    private javax.swing.JTextField tfSecondPerson;
    // End of variables declaration//GEN-END:variables
}
