/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bean.Question;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.Timer;
import service.QuestionService;
import service.QuestionServiceImpl;

/**
 *
 * @author OS
 */
public class MainFrame extends javax.swing.JFrame {

    private final QuestionService service;
    private JButton[] btQuestions;
    private JButton[] btWords;
    private Question currentQuestion;
    private int i = 0;
    private static final long START = 12000;

    public MainFrame() {
        service = new QuestionServiceImpl();

        initComponents();
        initComponentsManually();
        initEvents();
    }

    private void initEvents() {
        btQuestionEvents();
        btStartEvents();
    }

    private void btOpenEvents() {
        if (btWords == null) {
            return;
        }

        btOpen.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                for (JButton btWord : btWords) {
                    btWord.setText(btWord.getName());
                }
            }
        });
    }

    private void btStartEvents() {
        Timer timer = new Timer(1000, )
    }

    private void btWordEvents() {
        if (btWords == null) {
            return;
        }

        for (JButton btWord : btWords) {
            btWord.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    btWord.setText(btWord.getName());
                }
            });
        }
    }

    private void btQuestionEvents() {
        for (JButton btQuestion : btQuestions) {
            btQuestion.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    currentQuestion = service.getQuestionById(btQuestion.getName());
                    lbQuestion.setText(currentQuestion.getQuestion());
                    btWords = new JButton[currentQuestion.getAnswer().length()];
                    initBtWords(currentQuestion);
                    btWordEvents();
                    btOpenEvents();
                }
            });
        }
    }

    private void initBtWords(Question question) {
        String answer = question.getAnswer();
        pnCenterTop.removeAll();
        for (int i = 0; i < answer.length(); i++) {
            btWords[i] = new JButton();
            btWords[i].setName(String.valueOf(answer.charAt(i)));
            btWords[i].setPreferredSize(new Dimension(100, 100));
            btWords[i].setFocusPainted(false);
            btWords[i].setFont(new Font("TAHOMA", Font.BOLD, 40));
            pnCenterTop.add(btWords[i]);
        }
        pnCenterTop.revalidate();
        pnCenterTop.repaint();
    }

    private void initComponentsManually() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initBtnQuestion();
    }

    private void initBtnQuestion() {
        List<Question> questions = service.getAll();
        btQuestions = new JButton[questions.size()];
        for (int i = 0; i < questions.size(); i++) {
            btQuestions[i] = new JButton();
            btQuestions[i].setName(questions.get(i).getQuestionId());
            btQuestions[i].setText("Number" + i);
            pnTop.add(btQuestions[i]);
            pnTop.revalidate();
            pnTop.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        pnBottom = new javax.swing.JPanel();
        btStart = new javax.swing.JButton();
        btOpen = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        pnCenterTop = new javax.swing.JPanel();
        pnCenterBottom = new javax.swing.JPanel();
        pnCenterRight = new javax.swing.JPanel();
        lbClock = new javax.swing.JLabel();
        pnCenterLeft = new javax.swing.JPanel();
        pnQuestion = new javax.swing.JPanel();
        lbQuestion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btStart.setText("Bắt đầu");
        btStart.setFocusPainted(false);
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });
        pnBottom.add(btStart);

        btOpen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btOpen.setText("Mở ô chữ");
        btOpen.setFocusPainted(false);
        pnBottom.add(btOpen);

        btDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btDelete.setText("Xóa ô chữ");
        btDelete.setFocusPainted(false);
        pnBottom.add(btDelete);

        getContentPane().add(pnBottom, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.BorderLayout());

        pnCenterTop.setBackground(new java.awt.Color(51, 255, 51));
        pnCenter.add(pnCenterTop, java.awt.BorderLayout.CENTER);

        pnCenterBottom.setLayout(new java.awt.BorderLayout());

        pnCenterRight.setBackground(new java.awt.Color(255, 255, 255));
        pnCenterRight.setLayout(new java.awt.BorderLayout());

        lbClock.setBackground(new java.awt.Color(255, 255, 255));
        lbClock.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        lbClock.setForeground(new java.awt.Color(255, 0, 0));
        lbClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock339.jpg"))); // NOI18N
        lbClock.setText("12");
        lbClock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnCenterRight.add(lbClock, java.awt.BorderLayout.CENTER);

        pnCenterBottom.add(pnCenterRight, java.awt.BorderLayout.LINE_END);

        pnCenterLeft.setLayout(new java.awt.BorderLayout());

        lbQuestion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pnQuestion.add(lbQuestion);

        pnCenterLeft.add(pnQuestion, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dog.gif"))); // NOI18N
        jPanel1.add(jLabel1);

        pnCenterLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnCenterBottom.add(pnCenterLeft, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnCenterBottom, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btOpen;
    private javax.swing.JButton btStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbClock;
    private javax.swing.JLabel lbQuestion;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnCenterBottom;
    private javax.swing.JPanel pnCenterLeft;
    private javax.swing.JPanel pnCenterRight;
    private javax.swing.JPanel pnCenterTop;
    private javax.swing.JPanel pnQuestion;
    private javax.swing.JPanel pnTop;
    // End of variables declaration//GEN-END:variables
}
