/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

/**
 *
 * @author ADMIN
 */
public class PanelStudent extends javax.swing.JPanel {

    /**
     * Creates new form PanelStudent
     */
    public PanelStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        pnCenterLeft = new javax.swing.JPanel();
        pnCtLeftLb = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbHobbies = new javax.swing.JLabel();
        pnCtLeftTf = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        pnCenterRight = new javax.swing.JPanel();
        pnCtRightLb = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnCtRightTf = new javax.swing.JPanel();
        pnCtRightTop = new javax.swing.JPanel();
        tfMathMark = new javax.swing.JTextField();
        tfLiteratureMark = new javax.swing.JTextField();
        pnCtRightBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComment = new javax.swing.JTextArea();
        pnBottom = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(690, 425));
        setLayout(new java.awt.BorderLayout());

        pnTop.setPreferredSize(new java.awt.Dimension(690, 105));

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64px_flower.png"))); // NOI18N
        pnTop.add(lbImage);

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 153));
        lbTitle.setText("THÔNG TIN HỌC VIÊN");
        pnTop.add(lbTitle);

        add(pnTop, java.awt.BorderLayout.NORTH);

        pnCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        pnCenter.setPreferredSize(new java.awt.Dimension(0, 285));
        pnCenter.setLayout(new java.awt.GridLayout(0, 2));

        pnCenterLeft.setLayout(new java.awt.BorderLayout());

        pnCtLeftLb.setPreferredSize(new java.awt.Dimension(80, 655));
        pnCtLeftLb.setLayout(new java.awt.GridLayout(6, 0));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbName.setText("Họ tên:");
        pnCtLeftLb.add(lbName);

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbClass.setText("Lớp:");
        pnCtLeftLb.add(lbClass);

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbGender.setText("Giới tính:");
        pnCtLeftLb.add(lbGender);

        lbHobbies.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHobbies.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHobbies.setText("Sở thích:");
        pnCtLeftLb.add(lbHobbies);

        pnCenterLeft.add(pnCtLeftLb, java.awt.BorderLayout.WEST);

        pnCtLeftTf.setPreferredSize(new java.awt.Dimension(250, 655));
        pnCtLeftTf.setLayout(new java.awt.GridLayout(6, 0, 0, 15));
        pnCtLeftTf.add(jTextField1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14T4", "Item 2", "Item 3", "Item 4" }));
        pnCtLeftTf.add(jComboBox1);

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Nam");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setText("Nữ");
        jPanel1.add(jRadioButton2);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton3.setText("Khác");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jRadioButton3);

        pnCtLeftTf.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(0, 3));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText("Đá bóng");
        jPanel2.add(jCheckBox1);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox2.setText("Chơi bóng");
        jPanel2.add(jCheckBox2);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox3.setText("Bị bóng");
        jCheckBox3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jCheckBox3);

        pnCtLeftTf.add(jPanel2);

        pnCenterLeft.add(pnCtLeftTf, java.awt.BorderLayout.EAST);

        pnCenter.add(pnCenterLeft);

        pnCenterRight.setLayout(new java.awt.BorderLayout());

        pnCtRightLb.setPreferredSize(new java.awt.Dimension(110, 655));
        pnCtRightLb.setLayout(new java.awt.GridLayout(6, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Điểm Toán:");
        pnCtRightLb.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Điểm Văn:");
        pnCtRightLb.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nhận xét:");
        pnCtRightLb.add(jLabel3);

        pnCenterRight.add(pnCtRightLb, java.awt.BorderLayout.WEST);

        pnCtRightTf.setPreferredSize(new java.awt.Dimension(230, 655));
        pnCtRightTf.setLayout(new java.awt.BorderLayout());

        pnCtRightTop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnCtRightTop.setPreferredSize(new java.awt.Dimension(0, 86));
        pnCtRightTop.setLayout(new java.awt.GridLayout(2, 0, 0, 15));
        pnCtRightTop.add(tfMathMark);
        pnCtRightTop.add(tfLiteratureMark);

        pnCtRightTf.add(pnCtRightTop, java.awt.BorderLayout.NORTH);

        pnCtRightBottom.setPreferredSize(new java.awt.Dimension(0, 190));
        pnCtRightBottom.setRequestFocusEnabled(false);

        taComment.setColumns(20);
        taComment.setRows(5);
        taComment.setPreferredSize(new java.awt.Dimension(164, 50));
        jScrollPane1.setViewportView(taComment);

        javax.swing.GroupLayout pnCtRightBottomLayout = new javax.swing.GroupLayout(pnCtRightBottom);
        pnCtRightBottom.setLayout(pnCtRightBottomLayout);
        pnCtRightBottomLayout.setHorizontalGroup(
            pnCtRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnCtRightBottomLayout.setVerticalGroup(
            pnCtRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCtRightBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pnCtRightTf.add(pnCtRightBottom, java.awt.BorderLayout.SOUTH);

        pnCenterRight.add(pnCtRightTf, java.awt.BorderLayout.EAST);

        pnCenter.add(pnCenterRight);

        add(pnCenter, java.awt.BorderLayout.CENTER);

        pnBottom.setPreferredSize(new java.awt.Dimension(690, 35));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Submit");
        pnBottom.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Reset");
        pnBottom.add(jButton4);

        add(pnBottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbHobbies;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnCenterLeft;
    private javax.swing.JPanel pnCenterRight;
    private javax.swing.JPanel pnCtLeftLb;
    private javax.swing.JPanel pnCtLeftTf;
    private javax.swing.JPanel pnCtRightBottom;
    private javax.swing.JPanel pnCtRightLb;
    private javax.swing.JPanel pnCtRightTf;
    private javax.swing.JPanel pnCtRightTop;
    private javax.swing.JPanel pnTop;
    private javax.swing.JTextArea taComment;
    private javax.swing.JTextField tfLiteratureMark;
    private javax.swing.JTextField tfMathMark;
    // End of variables declaration//GEN-END:variables
}
