/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

/**
 *
 * @author USER
 */
public class PnHomePage extends javax.swing.JPanel {

    /**
     * Creates new form PnHomePage
     */
    public PnHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHomePage = new javax.swing.JLabel();

        lbHomePage.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbHomePage.setForeground(new java.awt.Color(255, 0, 0));
        lbHomePage.setText("THIS IS HOME PAGE");
        add(lbHomePage);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHomePage;
    // End of variables declaration//GEN-END:variables
}
