/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import model.StudentTableModel;
import view.FrAddStudent;

/**
 *
 * @author DangHoang
 */
public class PanelStudent extends javax.swing.JPanel {

    private final Font font = new Font("Tahoma", Font.PLAIN, 13);

    /**
     * Creates new form PanelStudent
     */
    public PanelStudent() {
        initComponents();
        initComponentsManually();
        initEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        pnBot = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbClassName = new javax.swing.JLabel();
        lbIsGender = new javax.swing.JLabel();
        lbHobbies = new javax.swing.JLabel();
        lbMath = new javax.swing.JLabel();
        lbLiterature = new javax.swing.JLabel();
        lbLiteratureScore = new javax.swing.JLabel();
        lbMathScore = new javax.swing.JLabel();
        lbHobbiesName = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        pnMainCenter = new javax.swing.JPanel();
        spStudent = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(0, 153, 204));
        pnTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        lbSearch.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbSearch.setText("Tìm kiếm :");

        tfSearch.setPreferredSize(new java.awt.Dimension(7, 30));

        btAdd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btAdd.setText("THÊM");

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbSearch)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(btAdd)
                .addGap(50, 50, 50))
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbSearch)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnBot.setBackground(new java.awt.Color(255, 102, 255));
        pnBot.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2), " THÔNG TIN SINH VIÊN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        pnBot.setPreferredSize(new java.awt.Dimension(800, 150));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbName.setText("Họ tên :");

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClass.setText("Lớp :");

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbGender.setText("Giới tính :");

        lbFullName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFullName.setText(".....................");

        lbClassName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClassName.setText(".....................");

        lbIsGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbIsGender.setText(".....................");

        lbHobbies.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbHobbies.setText("Sở thích :");

        lbMath.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbMath.setText("Toán :");

        lbLiterature.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbLiterature.setText("Văn :");

        lbLiteratureScore.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbLiteratureScore.setText(".....................");

        lbMathScore.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbMathScore.setText(".....................");

        lbHobbiesName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbHobbiesName.setText(".....................");

        lbAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

        btEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editor.png"))); // NOI18N
        btEdit.setText("SỬA");

        javax.swing.GroupLayout pnBotLayout = new javax.swing.GroupLayout(pnBot);
        pnBot.setLayout(pnBotLayout);
        pnBotLayout.setHorizontalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(lbClass)
                    .addComponent(lbGender))
                .addGap(26, 26, 26)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIsGender)
                    .addComponent(lbClassName)
                    .addComponent(lbFullName))
                .addGap(58, 58, 58)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHobbies)
                    .addComponent(lbMath)
                    .addComponent(lbLiterature))
                .addGap(26, 26, 26)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLiteratureScore)
                    .addComponent(lbMathScore)
                    .addComponent(lbHobbiesName))
                .addGap(79, 79, 79)
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btEdit)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnBotLayout.setVerticalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBotLayout.createSequentialGroup()
                        .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbHobbiesName)
                            .addComponent(lbName)
                            .addComponent(lbFullName)
                            .addComponent(lbHobbies))
                        .addGap(18, 18, 18)
                        .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbClass)
                            .addComponent(lbClassName)
                            .addComponent(lbMath)
                            .addComponent(lbMathScore))
                        .addGap(18, 18, 18)
                        .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbGender)
                            .addComponent(lbIsGender)
                            .addComponent(lbLiterature)
                            .addComponent(lbLiteratureScore))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnBotLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnBot, java.awt.BorderLayout.PAGE_END);

        pnMainCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        pnMainCenter.setLayout(new java.awt.BorderLayout());

        tbStudent.setAutoCreateRowSorter(true);
        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spStudent.setViewportView(tbStudent);

        pnMainCenter.add(spStudent, java.awt.BorderLayout.CENTER);

        add(pnMainCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btEdit;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbClassName;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbHobbies;
    private javax.swing.JLabel lbHobbiesName;
    private javax.swing.JLabel lbIsGender;
    private javax.swing.JLabel lbLiterature;
    private javax.swing.JLabel lbLiteratureScore;
    private javax.swing.JLabel lbMath;
    private javax.swing.JLabel lbMathScore;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JPanel pnBot;
    private javax.swing.JPanel pnMainCenter;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane spStudent;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    private void initComponentsManually() {
        tbStudent.setFont(font);
        tbStudent.setRowHeight(20);
        tbStudent.setCursor(new Cursor(Cursor.HAND_CURSOR));
        tbStudent.setModel(new StudentTableModel());
    }

    private void initEvents() {
        btAdd.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                new FrAddStudent().setVisible(true);
            }
        });
        
        btEdit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
            }
        });
    }
}