/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.WindowConstants;
import model.studentTableModel;

/**
 *
 * @author Admin
 */
public class PnStudent extends javax.swing.JPanel {

    /**
     * Creates new form PnStudent
     */
    public PnStudent() {
        initComponents();
        initEvent();
        initDataModel();
    }
    private void initDataModel(){
        initTablleStudentModel();
    }
    private void  initTablleStudentModel(){
        tbstudent.setModel(new studentTableModel());
    }
    
    
    
    private void initEvent(){
        btaddEvent();
        bteditEvent();
        
    }
    
    
    private void btaddEvent(){
        btadd.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                FrStudentForm form = new FrStudentForm();
                form.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);//moi quan he moi.
                form.setVisible(true);
                
            }
            
        });
    }
    private void bteditEvent(){
         btedit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
              
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pntop = new javax.swing.JPanel();
        lbsearch = new javax.swing.JLabel();
        tfsearch = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        PNBot = new javax.swing.JPanel();
        lbname = new javax.swing.JLabel();
        lbfullname = new javax.swing.JLabel();
        lbclass = new javax.swing.JLabel();
        lblop = new javax.swing.JLabel();
        lbgrand = new javax.swing.JLabel();
        lbgioitinh = new javax.swing.JLabel();
        lbsothich = new javax.swing.JLabel();
        lblike = new javax.swing.JLabel();
        lbmath = new javax.swing.JLabel();
        lbdiemtoan = new javax.swing.JLabel();
        lbdiemvan = new javax.swing.JLabel();
        lbvan = new javax.swing.JLabel();
        lbavatar = new javax.swing.JLabel();
        btedit = new javax.swing.JButton();
        PNMid = new javax.swing.JPanel();
        scrol = new javax.swing.JScrollPane();
        tbstudent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lbsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbsearch.setText("Tìm Kiếm");

        tfsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        btadd.setText("Thêm");

        javax.swing.GroupLayout pntopLayout = new javax.swing.GroupLayout(pntop);
        pntop.setLayout(pntopLayout);
        pntopLayout.setHorizontalGroup(
            pntopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pntopLayout.setVerticalGroup(
            pntopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pntopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btadd)
                    .addGroup(pntopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfsearch)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(pntop, java.awt.BorderLayout.PAGE_START);

        PNBot.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 255, 51))); // NOI18N
        PNBot.setToolTipText("");
        PNBot.setName(""); // NOI18N

        lbname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbname.setText("Họ Tên: ");

        lbfullname.setText("..................");

        lbclass.setText("..................");

        lblop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblop.setText("Lớp");

        lbgrand.setText("..................");

        lbgioitinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbgioitinh.setText("Giới Tính");

        lbsothich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsothich.setText("Sở Thích");

        lblike.setText("..................");

        lbmath.setText("..................");

        lbdiemtoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdiemtoan.setText("Điểm Toán");

        lbdiemvan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdiemvan.setText("Điểm Văn");

        lbvan.setText("..................");

        lbavatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        btedit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btedit.setText("Sửa");
        btedit.setToolTipText("");

        javax.swing.GroupLayout PNBotLayout = new javax.swing.GroupLayout(PNBot);
        PNBot.setLayout(PNBotLayout);
        PNBotLayout.setHorizontalGroup(
            PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNBotLayout.createSequentialGroup()
                        .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblop)
                            .addComponent(lbgioitinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNBotLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbclass))
                            .addGroup(PNBotLayout.createSequentialGroup()
                                .addComponent(lbgrand)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PNBotLayout.createSequentialGroup()
                        .addComponent(lbname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbfullname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdiemvan)
                    .addComponent(lbdiemtoan)
                    .addComponent(lbsothich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbvan)
                    .addComponent(lbmath)
                    .addComponent(lblike))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lbavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btedit))
        );
        PNBotLayout.setVerticalGroup(
            PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNBotLayout.createSequentialGroup()
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(lbfullname)
                    .addComponent(lbsothich)
                    .addComponent(lblike))
                .addGap(30, 30, 30)
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblop)
                    .addComponent(lbclass)
                    .addComponent(lbmath)
                    .addComponent(lbdiemtoan))
                .addGap(30, 30, 30)
                .addGroup(PNBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbgioitinh)
                    .addComponent(lbgrand)
                    .addComponent(lbdiemvan)
                    .addComponent(lbvan))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PNBotLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btedit)
                .addGap(38, 38, 38))
            .addComponent(lbavatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(PNBot, java.awt.BorderLayout.PAGE_END);

        PNMid.setLayout(new java.awt.BorderLayout());

        tbstudent.setAutoCreateRowSorter(true);
        tbstudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lớp", "Họ Tên", "Toán", "Văn", "Sở Thích"
            }
        ));
        scrol.setViewportView(tbstudent);

        PNMid.add(scrol, java.awt.BorderLayout.CENTER);

        add(PNMid, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PNBot;
    private javax.swing.JPanel PNMid;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btedit;
    private javax.swing.JLabel lbavatar;
    private javax.swing.JLabel lbclass;
    private javax.swing.JLabel lbdiemtoan;
    private javax.swing.JLabel lbdiemvan;
    private javax.swing.JLabel lbfullname;
    private javax.swing.JLabel lbgioitinh;
    private javax.swing.JLabel lbgrand;
    private javax.swing.JLabel lblike;
    private javax.swing.JLabel lblop;
    private javax.swing.JLabel lbmath;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbsearch;
    private javax.swing.JLabel lbsothich;
    private javax.swing.JLabel lbvan;
    private javax.swing.JPanel pntop;
    private javax.swing.JScrollPane scrol;
    private javax.swing.JTable tbstudent;
    private javax.swing.JTextField tfsearch;
    // End of variables declaration//GEN-END:variables
}
