/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.WindowConstants;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.StudentTableModel;
import model.bean.Student;
import service.StudentService;
import service.StudentServiceImpl;

/**
 *
 * @author khanh
 */
public class pnStudent extends javax.swing.JPanel {

    private final StudentService studentService;

    /**
     * Creates new form pnStudent
     */
    public pnStudent() {
        studentService = new StudentServiceImpl();
        initComponents();
        initEvents();

    }

    private void initEvents() {
        tfSearchEvents();
        btnAddEvents();
        initDataModel();
        btnEditEvents();
        tbStudentEvents();
    }

    private void tfSearchEvents() {
        tfSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String text = tfSearch.getText();
                TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbStudent.getModel());
                RowFilter<TableModel, Object> filter = null;

                tbStudent.setRowSorter(sorter);
                if (text.isEmpty()) {
                    filter = RowFilter.regexFilter(text);
                } else {
                    filter = RowFilter.regexFilter("^(?i)" + text + "$");
                }
                sorter.setRowFilter(filter);
            }

        });
    }

    private void tbStudentEvents() {
        tbStudent.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                tableRowSelectionTrigger();

            }
        });
        tbStudent.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                tableRowSelectionTrigger();
            }

        });
    }

    private void tableRowSelectionTrigger() {
        int rowIndex = tbStudent.getSelectedRow();
        int rowModel = tbStudent.convertColumnIndexToModel(rowIndex);
        String studentId = (String) tbStudent.getModel().getValueAt(rowModel, 0);
        Student student = studentService.get(studentId);
        setText(student);
    }

    private void setText(Student student) {
        lbName2.setText(student.getFullname());
        lbGender2.setText(student.getGender() ? "Nữ" : "Nam");
        lbHobbies2.setText(student.getHobbies());
        lbLiter2.setText(student.getLiterature().toString());
        lbMath2.setText(student.getMath().toString());
        lbGrade2.setText(student.getGrade().getName());
        if (student.getAvatarPath() != null) {
            Image image = new ImageIcon(student.getAvatarPath()).getImage()
                    .getScaledInstance(110, 110, Image.SCALE_SMOOTH);
            Icon icon = new ImageIcon(image);
            lbAvatar.setIcon(icon);
        }
    }

    private void initDataModel() {
        initTableStudentModel();
    }

    private void initTableStudentModel() {
        StudentTableModel studentModel = new StudentTableModel(tbStudent);
        studentModel.loadData();
        studentModel.cssForTable();
        
    }

    private void btnAddEvents() {
        btnAdd.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                FrStudentForm form = new FrStudentForm(tbStudent.getRowCount());
                form.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                form.setVisible(true);
            }

        });

    }

    private void btnEditEvents() {
        btnEdit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int rowIndex = tbStudent.getSelectedRow();
                int rowModel = tbStudent.convertColumnIndexToModel(rowIndex);
                String studentId = (String) tbStudent.getModel().getValueAt(rowModel, 0);
                Student student = studentService.get(studentId);

                FrStudentForm form = new FrStudentForm(student, tbStudent.getRowCount());
                form.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                form.setVisible(true);
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        pnBot = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbGrade = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbName2 = new javax.swing.JLabel();
        lbGrade2 = new javax.swing.JLabel();
        lbGender2 = new javax.swing.JLabel();
        lbHobbies = new javax.swing.JLabel();
        lbMath = new javax.swing.JLabel();
        lbLiter = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        lbHobbies2 = new javax.swing.JLabel();
        lbMath2 = new javax.swing.JLabel();
        lbLiter2 = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(0, 0, 204));

        lbSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSearch.setText("Tìm kiếm");

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setText("Thêm");

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbSearch)
                .addGap(90, 90, 90)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(81, 81, 81))
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTopLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearch)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(36, 36, 36))
        );

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnBot.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lbName.setText("Họ và tên:");

        lbGrade.setText("Lớp:");

        lbGender.setText("Giới Tính");

        lbName2.setText(".........");

        lbGrade2.setText(".........");

        lbGender2.setText(".........");

        lbHobbies.setText("Sở thích:");

        lbMath.setText("Điểm toán:");

        lbLiter.setText("Điểm văn:");

        lbAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbHobbies2.setText(".........");

        lbMath2.setText(".........");

        lbLiter2.setText(".........");

        javax.swing.GroupLayout pnBotLayout = new javax.swing.GroupLayout(pnBot);
        pnBot.setLayout(pnBotLayout);
        pnBotLayout.setHorizontalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGrade)
                    .addComponent(lbName)
                    .addComponent(lbGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName2)
                    .addComponent(lbGrade2)
                    .addComponent(lbGender2))
                .addGap(33, 33, 33)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHobbies)
                    .addComponent(lbMath)
                    .addComponent(lbLiter))
                .addGap(18, 18, 18)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHobbies2)
                    .addComponent(lbMath2)
                    .addComponent(lbLiter2))
                .addGap(77, 77, 77)
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addContainerGap())
        );
        pnBotLayout.setVerticalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotLayout.createSequentialGroup()
                .addComponent(btnEdit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnBotLayout.createSequentialGroup()
                            .addComponent(lbHobbies2)
                            .addGap(28, 28, 28)
                            .addComponent(lbMath2)
                            .addGap(29, 29, 29)
                            .addComponent(lbLiter2))
                        .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBotLayout.createSequentialGroup()
                                .addComponent(lbHobbies)
                                .addGap(28, 28, 28)
                                .addComponent(lbMath)
                                .addGap(29, 29, 29)
                                .addComponent(lbLiter))
                            .addGroup(pnBotLayout.createSequentialGroup()
                                .addComponent(lbName2)
                                .addGap(28, 28, 28)
                                .addComponent(lbGrade2)
                                .addGap(29, 29, 29)
                                .addComponent(lbGender2))
                            .addGroup(pnBotLayout.createSequentialGroup()
                                .addComponent(lbName)
                                .addGap(28, 28, 28)
                                .addComponent(lbGrade)
                                .addGap(29, 29, 29)
                                .addComponent(lbGender)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(pnBot, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.BorderLayout());

        tbStudent.setAutoCreateRowSorter(true);
        tbStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbStudent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbStudent);

        pnCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGender2;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbGrade2;
    private javax.swing.JLabel lbHobbies;
    private javax.swing.JLabel lbHobbies2;
    private javax.swing.JLabel lbLiter;
    private javax.swing.JLabel lbLiter2;
    private javax.swing.JLabel lbMath;
    private javax.swing.JLabel lbMath2;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JPanel pnBot;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnTop;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

}
