/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ButtonModel;

/**
 *
 * @author ADMIN
 */
public class PnStudentHome extends javax.swing.JPanel {

    /**
     * Creates new form PanelHomePage
     */
    public PnStudentHome() {
     
        initComponents();
        initComponentMatually();
        initEvents();
    }

    public void initComponentMatually() {
        btSubmit.setFocusPainted(false);
        btSubmit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btReset.setFocusPainted(false);
        btReset.setCursor(new Cursor(Cursor.HAND_CURSOR));
        rbMale.setSelected(true);
    }

    public void initEvents() {
        btSubmit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {

            }

        });
        btReset.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                tfName.setText("");
                tfMath.setText("");
                tfLiterature.setText("");
                taComment.setText("");
                comboClass.setSelectedIndex(0);
                rbMale.setSelected(true);
                cbBiBong.setSelected(false);
                cbChoiBong.setSelected(false);
                cbDaBong.setSelected(false);

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        pnTop = new javax.swing.JPanel();
        lbInfor = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbFavorite = new javax.swing.JLabel();
        lbMath = new javax.swing.JLabel();
        lbLiterature = new javax.swing.JLabel();
        lbComment = new javax.swing.JLabel();
        cbDaBong = new javax.swing.JCheckBox();
        cbChoiBong = new javax.swing.JCheckBox();
        cbBiBong = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComment = new javax.swing.JTextArea();
        tfLiterature = new javax.swing.JTextField();
        tfMath = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        rbDiff = new javax.swing.JRadioButton();
        comboClass = new javax.swing.JComboBox<>();
        pnBottom = new javax.swing.JPanel();
        btReset = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        setLayout(new java.awt.BorderLayout());

        lbInfor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbInfor.setForeground(new java.awt.Color(0, 0, 204));
        lbInfor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        lbInfor.setText("THÔNG TIN HỌC VIÊN");
        lbInfor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbInfor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTop.add(lbInfor);

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbName.setText("Họ tên:");

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbClass.setText("Lớp:");

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbGender.setText("Giới tính:");

        lbFavorite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFavorite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFavorite.setText("Sở thích:");

        lbMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMath.setText("Điểm toán:");

        lbLiterature.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLiterature.setText("Điểm văn:");

        lbComment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbComment.setText("Nhận xét:");

        cbDaBong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDaBong.setText("Đá bóng");

        cbChoiBong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbChoiBong.setText("Chơi bóng");
        cbChoiBong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChoiBongActionPerformed(evt);
            }
        });

        cbBiBong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbBiBong.setText("Bị bóng");

        taComment.setColumns(20);
        taComment.setRows(5);
        jScrollPane1.setViewportView(taComment);

        tfLiterature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLiteratureActionPerformed(evt);
            }
        });

        tfMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMathActionPerformed(evt);
            }
        });

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        bgGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbMale.setText("Nam");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        bgGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFemale.setText("Nữ");

        bgGender.add(rbDiff);
        rbDiff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbDiff.setText("Khác");

        comboClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14T1", "14T2", "14T3", "14T4" }));

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFavorite)
                    .addComponent(lbGender)
                    .addComponent(lbClass)
                    .addComponent(lbName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCenterLayout.createSequentialGroup()
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDaBong)
                            .addComponent(rbMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCenterLayout.createSequentialGroup()
                                .addComponent(rbFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbDiff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbComment))
                            .addGroup(pnCenterLayout.createSequentialGroup()
                                .addComponent(cbChoiBong)
                                .addGap(10, 10, 10)
                                .addComponent(cbBiBong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))))
                    .addGroup(pnCenterLayout.createSequentialGroup()
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboClass, 0, 184, Short.MAX_VALUE)
                            .addComponent(tfName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMath, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLiterature, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tfLiterature)
                    .addComponent(tfMath))
                .addContainerGap())
        );

        pnCenterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbClass, lbComment, lbFavorite, lbGender, lbLiterature, lbMath, lbName});

        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbName)
                        .addComponent(lbMath)
                        .addComponent(tfMath, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfName))
                .addGap(12, 12, 12)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClass)
                    .addComponent(lbLiterature)
                    .addComponent(tfLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCenterLayout.createSequentialGroup()
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGender)
                            .addComponent(lbComment)
                            .addComponent(rbMale)
                            .addComponent(rbFemale)
                            .addComponent(rbDiff))
                        .addGap(20, 20, 20)
                        .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFavorite)
                            .addComponent(cbDaBong)
                            .addComponent(cbChoiBong)
                            .addComponent(cbBiBong)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnCenterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboClass, tfLiterature, tfMath, tfName});

        add(pnCenter, java.awt.BorderLayout.CENTER);

        btReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btReset.setText("Reset");

        btSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBottomLayout = new javax.swing.GroupLayout(pnBottom);
        pnBottom.setLayout(pnBottomLayout);
        pnBottomLayout.setHorizontalGroup(
            pnBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReset)
                .addContainerGap())
        );

        pnBottomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btReset, btSubmit});

        pnBottomLayout.setVerticalGroup(
            pnBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(pnBottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubmitActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void tfMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMathActionPerformed

    private void cbChoiBongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChoiBongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChoiBongActionPerformed

    private void tfLiteratureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLiteratureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLiteratureActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSubmit;
    private javax.swing.JCheckBox cbBiBong;
    private javax.swing.JCheckBox cbChoiBong;
    private javax.swing.JCheckBox cbDaBong;
    private javax.swing.JComboBox<String> comboClass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbComment;
    private javax.swing.JLabel lbFavorite;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbInfor;
    private javax.swing.JLabel lbLiterature;
    private javax.swing.JLabel lbMath;
    private javax.swing.JLabel lbName;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnTop;
    private javax.swing.JRadioButton rbDiff;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextArea taComment;
    private javax.swing.JTextField tfLiterature;
    private javax.swing.JTextField tfMath;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
