/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.FrStudentForm;

/**
 *
 * @author DangHoang
 */
public class PnStudent extends javax.swing.JPanel {

    private final Font font = new Font("Tahoma", Font.PLAIN, 13);
    private DefaultTableModel dftmStudent;
    private String[] columnName;

    /**
     * Creates new form PanelStudent
     *
     */
    public PnStudent() {
        initComponents();

        addTable();

        initEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        pnBot = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbClass = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbClassName = new javax.swing.JLabel();
        lbIsGender = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        lbClass1 = new javax.swing.JLabel();
        lbGender1 = new javax.swing.JLabel();
        lbIsGender1 = new javax.swing.JLabel();
        lbClassName1 = new javax.swing.JLabel();
        lbFullName1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        spStudent = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(102, 102, 255));
        pnTop.setPreferredSize(new java.awt.Dimension(800, 50));

        lbSearch.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbSearch.setText("Tìm kiếm : ");

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfSearch.setPreferredSize(new java.awt.Dimension(220, 30));

        btAdd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btAdd.setText("THÊM");

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbSearch)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(btAdd)
                .addGap(75, 75, 75))
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSearch)
                    .addComponent(btAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnBot.setBackground(new java.awt.Color(255, 153, 153));
        pnBot.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN SINH VIÊN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        pnBot.setPreferredSize(new java.awt.Dimension(800, 150));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbName.setText("Họ tên : ");

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClass.setText("Lớp :");

        lbGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbGender.setText("Giới tính :");

        lbFullName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFullName.setText("....................");

        lbClassName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClassName.setText("....................");

        lbIsGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbIsGender.setText("....................");

        lbName1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbName1.setText("Sở thích :");

        lbClass1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClass1.setText("Điểm toán :");

        lbGender1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbGender1.setText("Điểm văn :");

        lbIsGender1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbIsGender1.setText("....................");

        lbClassName1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbClassName1.setText("....................");

        lbFullName1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFullName1.setText("....................");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editor.png"))); // NOI18N
        jButton1.setText("Sửa");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnBotLayout = new javax.swing.GroupLayout(pnBot);
        pnBot.setLayout(pnBotLayout);
        pnBotLayout.setHorizontalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(lbClass)
                    .addComponent(lbGender))
                .addGap(30, 30, 30)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIsGender)
                    .addComponent(lbClassName)
                    .addComponent(lbFullName))
                .addGap(37, 37, 37)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName1)
                    .addComponent(lbClass1)
                    .addComponent(lbGender1))
                .addGap(30, 30, 30)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIsGender1)
                    .addComponent(lbClassName1)
                    .addComponent(lbFullName1))
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        pnBotLayout.setVerticalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBotLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbFullName)
                    .addComponent(lbName1)
                    .addComponent(lbFullName1))
                .addGap(18, 18, 18)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClass)
                    .addComponent(lbClassName)
                    .addComponent(lbClass1)
                    .addComponent(lbClassName1))
                .addGap(18, 18, 18)
                .addGroup(pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGender)
                    .addComponent(lbIsGender)
                    .addComponent(lbGender1)
                    .addComponent(lbIsGender1))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnBotLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnBot, java.awt.BorderLayout.PAGE_END);

        pnCenter.setBackground(new java.awt.Color(0, 204, 255));
        pnCenter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnCenter.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        pnCenter.setPreferredSize(new java.awt.Dimension(800, 300));

        tbStudent.setBackground(new java.awt.Color(204, 255, 255));
        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spStudent.setViewportView(tbStudent);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton btAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbClass1;
    private javax.swing.JLabel lbClassName;
    private javax.swing.JLabel lbClassName1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbFullName1;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGender1;
    private javax.swing.JLabel lbIsGender;
    private javax.swing.JLabel lbIsGender1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JPanel pnBot;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane spStudent;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration                   

    private void addTable() {
        dftmStudent = new DefaultTableModel();
        columnName = new String[]{"Lớp", "Họ tên", "Toán", "Văn", "Sở thích"};

        tbStudent.setModel(dftmStudent);
        tbStudent.setFont(font);
        tbStudent.setCursor(new Cursor(Cursor.HAND_CURSOR));
        tbStudent.setRowHeight(20);
        setColumnsTableName();
        setDataRowsTable();
        spStudent.setViewportView(tbStudent);
        pnCenter.add(spStudent);
    }

    private void setColumnsTableName() {
        dftmStudent.addColumn(columnName);
        dftmStudent.setColumnIdentifiers(columnName);

        tbStudent.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbStudent.getColumnModel().getColumn(0).setWidth(pnCenter.getWidth() / 10);
        tbStudent.getColumnModel().getColumn(0).setWidth(pnCenter.getWidth() * 4 / 10);
        tbStudent.getColumnModel().getColumn(0).setWidth(pnCenter.getWidth() / 10);
        tbStudent.getColumnModel().getColumn(0).setWidth(pnCenter.getWidth() / 10);
        tbStudent.getColumnModel().getColumn(0).setWidth(pnCenter.getWidth() * 3 / 10);
    }

    private void setDataRowsTable() {
    }

    private void initEvents() {
        btAdd.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                new FrStudentForm().setVisible(true);
            }
        });
        jButton1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                
            }
            
        });
    }
    
    
}