/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import bean.model.grade;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.AbstractButton;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Trung
 */
public class Student extends javax.swing.JPanel {

    private File targetFile;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        initDataModel();
        initEvents();
    }

    private void initDataModel() {
        initCbbGradeModel();

    }

    private void pnUploadEvents() {
        button1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                String path = getClass().getResource("/images.ghost").getFile();
                JFileChooser fc = new JFileChooser(path);
                int chooser = fc.showDialog(null, "Upload");
                if (chooser == JFileChooser.APPROVE_OPTION) {
                    File sourceFile = fc.getSelectedFile();
                    String fileName = sourceFile.getName();

                    String regex = "[\\w-]+[.]{1}(?i)(?:png|jpg|jpeg|gif)";
                    if (!(fileName.matches(regex))) {
                        JOptionPane.showMessageDialog(null, "INVALID IMAGE PATH");
                        return;
                    }
                    String renameFile = System.currentTimeMillis() + fileName;
                    targetFile = new File("image_upload" + File.separator + renameFile);
                    try {
                        Files.copy(sourceFile.toPath(), targetFile.toPath());
                    } catch (IOException ex) {
                        Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Image image = new ImageIcon(targetFile.getPath()).getImage().getScaledInstance(LB.getWidth(), LB.getHeight(), Image.SCALE_SMOOTH);
                    Icon icon = new ImageIcon(image);
                    LB.setIcon(icon);

                }

            }

        });

    }

    private void initCbbGradeModel() {
        grade[] grade = {
            new grade(1, "11T1"),
            new grade(1, "12T1"),
            new grade(1, "13T1"),
            new grade(1, "14T1"),
            new grade(1, "15T1")
        };
        ComboBoxModel<grade> gradeModels = new DefaultComboBoxModel<>(grade);
        cbbclass.setModel(gradeModels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnMainBot = new javax.swing.JPanel();
        btSubmit = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        pnMainTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        lbName1 = new javax.swing.JLabel();
        cbbclass = new javax.swing.JComboBox();
        lbGT = new javax.swing.JLabel();
        lbST = new javax.swing.JLabel();
        RBMale = new javax.swing.JRadioButton();
        RBFemale = new javax.swing.JRadioButton();
        RBother = new javax.swing.JRadioButton();
        CBBD = new javax.swing.JCheckBox();
        CBBC = new javax.swing.JCheckBox();
        CBCL = new javax.swing.JCheckBox();
        pnRight = new javax.swing.JPanel();
        LbMath = new javax.swing.JLabel();
        TFMath = new javax.swing.JTextField();
        LBlite = new javax.swing.JLabel();
        TFLite = new javax.swing.JTextField();
        lbComment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LBImage = new javax.swing.JLabel();
        LB = new javax.swing.JLabel();
        button1 = new java.awt.Button();

        setLayout(new java.awt.BorderLayout());

        btSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSubmit.setText("SUBMIT");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        btReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btReset.setText("RESET");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMainBotLayout = new javax.swing.GroupLayout(pnMainBot);
        pnMainBot.setLayout(pnMainBotLayout);
        pnMainBotLayout.setHorizontalGroup(
            pnMainBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainBotLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btSubmit)
                .addGap(18, 18, 18)
                .addComponent(btReset)
                .addContainerGap(687, Short.MAX_VALUE))
        );
        pnMainBotLayout.setVerticalGroup(
            pnMainBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainBotLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(pnMainBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSubmit)
                    .addComponent(btReset))
                .addGap(24, 24, 24))
        );

        add(pnMainBot, java.awt.BorderLayout.PAGE_END);

        pnMainTop.setPreferredSize(new java.awt.Dimension(559, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dangh\\Desktop\\java07-app\\Lesson20\\target\\classes\\images\\student.png")); // NOI18N
        jLabel2.setText("THÔNG TIN HỌC VIÊN");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnMainTop.add(jLabel2);

        add(pnMainTop, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnLeft.setBackground(new java.awt.Color(153, 255, 255));
        pnLeft.setForeground(new java.awt.Color(0, 255, 255));
        pnLeft.setPreferredSize(new java.awt.Dimension(400, 369));
        pnLeft.setVerifyInputWhenFocusTarget(false);

        lbName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbName.setText("Họ Tên:");

        tfHoTen.setPreferredSize(new java.awt.Dimension(6, 32));
        tfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenActionPerformed(evt);
            }
        });

        lbName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbName1.setText("Lớp:");

        cbbclass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbclassActionPerformed(evt);
            }
        });

        lbGT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGT.setText("Gioi tính:");

        lbST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbST.setText("Sở thích :");

        buttonGroup1.add(RBMale);
        RBMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBMale.setText("Nam");
        RBMale.setFocusPainted(false);
        RBMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBFemale);
        RBFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBFemale.setText("Nữ");
        RBFemale.setFocusPainted(false);

        buttonGroup1.add(RBother);
        RBother.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBother.setText("Khác");
        RBother.setFocusPainted(false);
        RBother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBotherActionPerformed(evt);
            }
        });

        CBBD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CBBD.setText("Bóng đá");
        CBBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBDActionPerformed(evt);
            }
        });

        CBBC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CBBC.setText("Bóng chuyền");

        CBCL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CBCL.setText("Cầu lông");

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(lbName1)
                    .addComponent(lbGT)
                    .addComponent(lbST))
                .addGap(18, 18, 18)
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBBD)
                            .addComponent(RBMale))
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBFemale)
                            .addComponent(CBBC))
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBCL)
                            .addComponent(RBother))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbGT)
                                    .addComponent(RBMale)
                                    .addComponent(RBFemale)
                                    .addComponent(RBother)))
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbclass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbName1))))
                        .addGap(21, 21, 21)
                        .addComponent(lbST))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBBD)
                            .addComponent(CBBC)
                            .addComponent(CBCL))))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(pnLeft);

        pnRight.setBackground(new java.awt.Color(255, 255, 102));
        pnRight.setPreferredSize(new java.awt.Dimension(294, 423));

        LbMath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbMath.setText("Điểm toán:");

        TFMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMathActionPerformed(evt);
            }
        });

        LBlite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBlite.setText("Điểm Văn:");

        TFLite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLiteActionPerformed(evt);
            }
        });

        lbComment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbComment.setText("Nhận xét:");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        LBImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBImage.setText("Hình ảnh:");

        LB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 2));

        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbMath)
                    .addComponent(LBlite)
                    .addComponent(lbComment)
                    .addComponent(LBImage))
                .addGap(18, 18, 18)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFLite)
                    .addComponent(TFMath)
                    .addComponent(jScrollPane1)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addComponent(LB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbMath)
                    .addComponent(TFMath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TFLite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBlite))
                .addGap(18, 18, 18)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbComment)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(LBImage)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnRightLayout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        jSplitPane1.setRightComponent(pnRight);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResetActionPerformed

    private void tfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenActionPerformed

    private void RBMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBMaleActionPerformed

    private void RBotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBotherActionPerformed

    private void CBBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBDActionPerformed

    private void TFMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMathActionPerformed

    private void TFLiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLiteActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void cbbclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbclassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBBC;
    private javax.swing.JCheckBox CBBD;
    private javax.swing.JCheckBox CBCL;
    private javax.swing.JLabel LB;
    private javax.swing.JLabel LBImage;
    private javax.swing.JLabel LBlite;
    private javax.swing.JLabel LbMath;
    private javax.swing.JRadioButton RBFemale;
    private javax.swing.JRadioButton RBMale;
    private javax.swing.JRadioButton RBother;
    private javax.swing.JTextField TFLite;
    private javax.swing.JTextField TFMath;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSubmit;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbbclass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbComment;
    private javax.swing.JLabel lbGT;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbST;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMainBot;
    private javax.swing.JPanel pnMainTop;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTextField tfHoTen;
    // End of variables declaration//GEN-END:variables

    private void initEvents() {
        pnUploadEvents();
        btSubmitEvents();
    }

    private void btSubmitEvents() {
        btSubmit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                grade gradee = (grade) cbbclass.getSelectedItem();
                String gender = getGender();
                String hobbies = getHobbies(CBBC, CBBD, CBCL);
                String filename = targetFile != null ? targetFile.getName() : "UnderFined";
                System.out.println("Gioi tinh: " + gender);
                System.out.println("so thich:" + hobbies);
                System.out.println("ho ten: "+tfHoTen.getText());
            }

        });
    }

    private String getGender() {
        Enumeration<AbstractButton> elements = buttonGroup1.getElements();
        while (elements.hasMoreElements()) {
            AbstractButton button = elements.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "";
    }

    private String getHobbies(JCheckBox... checkBoxs) {
        return Arrays.stream(checkBoxs).filter(JCheckBox::isSelected).map(JCheckBox::getText).collect(Collectors.joining());
    }
}
