/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import service.TimeService;
import service.TimeServiceImpl;

/**
 *
 * @author ADMIN
 */
public class Ex05 extends javax.swing.JFrame {

    private Container conn = getContentPane();
    private final TimeService timeService;

    public Ex05() {
        timeService = new TimeServiceImpl();
        
        initComponents();
        initComponentManually();
        initEvents();
    }

    private void initComponentManually() {
        setResizable(false);
        setLocationRelativeTo(null);
        Image image = new ImageIcon(getClass().getResource("/images/48px_love.png")).getImage();
        setIconImage(image);
        conn.setBackground(Color.BLACK);
        dcEnd.setDate(new Date());
    }

    private void initEvents() {
        btLoveEvent();
    }

    private void btLoveEvent() {
        btLove.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                final String firstName=tfFirstPerson.getText();
                final String secondName=tfSecondPerson.getText();
                final Date start=dcStart.getDate();
                final Date end=dcEnd.getDate();
                
                Period period =timeService.getPeriod(start, end);
                
                lbResult.setText("Kết quả : "+
                        firstName+" và "+
                        secondName+" quen nhau "+
                        period.getYears()+" năm" +
                        period.getMonths()+" tháng,"+
                        period.getDays()+" ngày.");
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbFirstError = new javax.swing.JLabel();
        tfFirstPerson = new javax.swing.JTextField();
        lbResult = new javax.swing.JLabel();
        btLike = new javax.swing.JButton();
        lbSecondPerson = new javax.swing.JLabel();
        tfSecondPerson = new javax.swing.JTextField();
        lbSecondError = new javax.swing.JLabel();
        btLove = new javax.swing.JButton();
        lbEnd = new javax.swing.JLabel();
        lbStart = new javax.swing.JLabel();
        dcStart = new com.toedter.calendar.JDateChooser();
        dcEnd = new com.toedter.calendar.JDateChooser();
        lbFirstPerson1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love - Time Application");

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 0, 204));
        lbTitle.setText("Love Time Application");

        lbFirstError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 0, 0));
        lbFirstError.setText("            Chưa nhập tên");

        tfFirstPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstPersonActionPerformed(evt);
            }
        });

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResult.setForeground(new java.awt.Color(255, 255, 255));
        lbResult.setText("Kết quả");

        btLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_like.png"))); // NOI18N
        btLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLikeActionPerformed(evt);
            }
        });

        lbSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbSecondPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbSecondPerson.setText("   Người thứ hai:");

        tfSecondPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondPersonActionPerformed(evt);
            }
        });

        lbSecondError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSecondError.setForeground(new java.awt.Color(255, 0, 0));
        lbSecondError.setText("                Chưa nhập tên");

        btLove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_love.png"))); // NOI18N
        btLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoveActionPerformed(evt);
            }
        });

        lbEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbEnd.setText("Ngày kết thúc");

        lbStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStart.setForeground(new java.awt.Color(255, 255, 255));
        lbStart.setText("Ngày bắt đầu");

        dcStart.setDateFormatString("dd/MM/yyyy");

        dcEnd.setDateFormatString("dd/MM/yyyy");

        lbFirstPerson1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbFirstPerson1.setForeground(new java.awt.Color(255, 255, 255));
        lbFirstPerson1.setText("   Người thứ nhất:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbFirstError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbFirstPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(dcEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(230, 230, 230)
                        .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSecondError, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dcStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStart, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbFirstPerson1, tfFirstPerson});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcStart, lbEnd, lbStart});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbSecondError, lbSecondPerson});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSecondPerson)
                            .addComponent(lbStart))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(lbEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbFirstPerson1)
                        .addGap(28, 28, 28)
                        .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFirstError)
                            .addComponent(lbSecondError))
                        .addGap(51, 51, 51)
                        .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcEnd, dcStart, tfFirstPerson, tfSecondPerson});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFirstPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstPersonActionPerformed

    private void btLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLikeActionPerformed

    private void tfSecondPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondPersonActionPerformed

    private void btLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLike;
    private javax.swing.JButton btLove;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbFirstPerson1;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSecondError;
    private javax.swing.JLabel lbSecondPerson;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfFirstPerson;
    private javax.swing.JTextField tfSecondPerson;
    // End of variables declaration//GEN-END:variables
}
