/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import service.TimeSerViceImpl;
import service.TimeService;

/**
 *
 * @author DangHoang
 */
public class Ex05 extends javax.swing.JFrame {

    Container con = getContentPane();

    private final TimeService timeService;

    public Ex05() {
        timeService = new TimeSerViceImpl();

        initComponents();
        initComponentsManually();
        initEvents();
    }

    private void initComponentsManually() {
        setResizable(false);
        setLocationRelativeTo(null);

        Image image = new ImageIcon(getClass().getResource("/images/64px_flower.png")).getImage();
        setIconImage(image);

        con.setBackground(Color.BLACK);

        dcEnd.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbFirstPerson = new javax.swing.JLabel();
        tfFirstPerson = new javax.swing.JTextField();
        lbFirstError = new javax.swing.JLabel();
        btLike = new javax.swing.JButton();
        btLove = new javax.swing.JButton();
        lbSecondError = new javax.swing.JLabel();
        tfSecondPerson = new javax.swing.JTextField();
        lbSecondPerson = new javax.swing.JLabel();
        lbStart = new javax.swing.JLabel();
        dcStart = new com.toedter.calendar.JDateChooser();
        lbEnd = new javax.swing.JLabel();
        dcEnd = new com.toedter.calendar.JDateChooser();
        lbResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love - Time Application");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 0, 204));
        lbTitle.setText("Love - Time Application");

        lbFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbFirstPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbFirstPerson.setText("- Người thứ nhất -");

        tfFirstPerson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFirstPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstPersonActionPerformed(evt);
            }
        });

        lbFirstError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 0, 0));
        lbFirstError.setText("Chưa nhập tên");

        btLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_like.png"))); // NOI18N
        btLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLikeActionPerformed(evt);
            }
        });

        btLove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48px_love.png"))); // NOI18N
        btLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoveActionPerformed(evt);
            }
        });

        lbSecondError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSecondError.setForeground(new java.awt.Color(255, 0, 0));
        lbSecondError.setText("Chưa nhập tên");

        tfSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSecondPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondPersonActionPerformed(evt);
            }
        });

        lbSecondPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSecondPerson.setForeground(new java.awt.Color(255, 255, 255));
        lbSecondPerson.setText("- Người thứ hai -");

        lbStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStart.setForeground(new java.awt.Color(255, 255, 255));
        lbStart.setText("- Ngày bắt đầu -");

        dcStart.setDateFormatString("dd/MM/yyyy");
        dcStart.setPreferredSize(new java.awt.Dimension(80, 20));

        lbEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbEnd.setText("- Ngày kết thúc -");

        dcEnd.setDateFormatString("dd/MM/yyyy");
        dcEnd.setPreferredSize(new java.awt.Dimension(80, 20));

        lbResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResult.setForeground(new java.awt.Color(255, 0, 0));
        lbResult.setText("- Kết quả: ");
        lbResult.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFirstPerson)
                            .addComponent(lbFirstError)
                            .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbStart)
                            .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEnd)
                            .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSecondPerson)
                            .addComponent(lbSecondError)
                            .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbFirstPerson)
                        .addComponent(lbStart))
                    .addComponent(lbSecondPerson))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfFirstPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSecondPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSecondError)
                        .addGap(11, 11, 11)
                        .addComponent(lbEnd))
                    .addComponent(lbFirstError))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLike, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLove, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lbResult)
                .addGap(43, 43, 43))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcEnd, dcStart, tfFirstPerson, tfSecondPerson});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLikeActionPerformed

    private void btLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoveActionPerformed

    private void tfSecondPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondPersonActionPerformed

    private void tfFirstPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstPersonActionPerformed

    private void initEvents() {
        btLoveEvents();
    }

    private void btLoveEvents() {
        btLove.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                final String first = tfFirstPerson.getText();
                final String second = tfSecondPerson.getText();
                final Date start = dcStart.getDate();
                final Date end = dcEnd.getDate();
                Period period = timeService.getPeriod(start, end);

                lbResult.setText("- Kết quả: " + first + " & " + second + " đã quen nhau " + period.getDays() + " ngày, "
                        + period.getMonths() + " tháng, " + period.getYears() + " năm.");
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay wilbStartdefault look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLike;
    private javax.swing.JButton btLove;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbFirstPerson;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSecondError;
    private javax.swing.JLabel lbSecondPerson;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfFirstPerson;
    private javax.swing.JTextField tfSecondPerson;
    // End of variables declaration//GEN-END:variables
}
